## Basics of Numpy


<b>Load numpy as np</b>

In [6]:
import numpy as np

<b> 1-D Array </b>

In [82]:
# a = np.array([1,3,5])
a = np.array([1,3,5,3,5], dtype = 'int16') # specify the dtype to less like int16 if no of integers are less to save memory space
print(a)
print(type(a))

[1 3 5 3 5]
<class 'numpy.ndarray'>


<b> 2-D Array </b>

In [85]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


#### Basic Operations

In [88]:
# Get Size
a.size

5

In [90]:
# Get no of dimensions
a.ndim  

1

In [92]:
# Get shape (return size of array in each dimension)
print(a.shape)
print(b.shape)

(5,)
(2, 3)


In [94]:
# Get data type
a.dtype

dtype('int16')

In [56]:
b.dtype

dtype('float64')

In [102]:
# Get individual item size in bytes
a.itemsize

2

In [100]:
# Get all items size in bytes
a.nbytes

10